fos_elastica:
    clients:
        default: { host: "%elastic_host%", port: "%elastic_port%" }
    indexes:
        example_index:
            client: default
            types:
                item:
                    mappings:
                        id:
                            type: integer
                        createdAt :
                            type : date
                        publishedAt :
                            type : date
                        published :
                            type : boolean
                        title : ~
                        content : ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Item
                        finder: ~
                        provider: ~
                        listener: ~
                        repository: AppBundle\SearchRepository\ItemRepository